// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file batteryVoltage.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "PacketTypes/batteryVoltage.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

class Header;

BatteryVoltage::BatteryVoltage()
{
    // m_head com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@5c18298f
    m_head = new Header();
    // m_volt com.eprosima.idl.parser.typecode.PrimitiveTypeCode@31f924f5
    m_volt = 0.0;

}

BatteryVoltage::~BatteryVoltage()
{
    delete m_head;

}

BatteryVoltage::BatteryVoltage(
        const BatteryVoltage& x)
{
    m_head = new Header();
    *m_head = *x.m_head;

    m_volt = x.m_volt;
}

BatteryVoltage::BatteryVoltage(
        BatteryVoltage&& x) noexcept 
{
    m_head = x.m_head;
    x.m_head = nullptr;
    m_volt = x.m_volt;
}

BatteryVoltage& BatteryVoltage::operator =(
        const BatteryVoltage& x)
{

    m_head = new Header();
    *m_head = *x.m_head;

    m_volt = x.m_volt;

    return *this;
}

BatteryVoltage& BatteryVoltage::operator =(
        BatteryVoltage&& x) noexcept
{

    m_head = x.m_head;
    x.m_head = nullptr;
    m_volt = x.m_volt;

    return *this;
}

bool BatteryVoltage::operator ==(
        const BatteryVoltage& x) const
{

    return (m_head == x.m_head && m_volt == x.m_volt);
}

bool BatteryVoltage::operator !=(
        const BatteryVoltage& x) const
{
    return !(*this == x);
}

size_t BatteryVoltage::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t BatteryVoltage::getCdrSerializedSize(
        const BatteryVoltage& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getCdrSerializedSize(data.head(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void BatteryVoltage::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << *m_head;
    scdr << m_volt;

}

void BatteryVoltage::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> *m_head;
    dcdr >> m_volt;
}

/*!
 * @brief This function copies the value in member head
 * @param _head New value to be copied in member head
 */
void BatteryVoltage::head(
        const Header& _head)
{
    *m_head = _head;
}

/*!
 * @brief This function moves the value in member head
 * @param _head New value to be moved in member head
 */
void BatteryVoltage::head(
        Header&& _head)
{
    *m_head = std::move(_head);
}

/*!
 * @brief This function returns a constant reference to member head
 * @return Constant reference to member head
 */
const Header& BatteryVoltage::head() const
{
    return *m_head;
}

/*!
 * @brief This function returns a reference to member head
 * @return Reference to member head
 */
Header& BatteryVoltage::head()
{
    return *m_head;
}
/*!
 * @brief This function sets a value in member volt
 * @param _volt New value for member volt
 */
void BatteryVoltage::volt(
        float _volt)
{
    m_volt = _volt;
}

/*!
 * @brief This function returns the value of member volt
 * @return Value of member volt
 */
float BatteryVoltage::volt() const
{
    return m_volt;
}

/*!
 * @brief This function returns a reference to member volt
 * @return Reference to member volt
 */
float& BatteryVoltage::volt()
{
    return m_volt;
}


size_t BatteryVoltage::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool BatteryVoltage::isKeyDefined()
{
    return false;
}

void BatteryVoltage::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
