// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file carTilt.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "PacketTypes/carTilt.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

CarTilt::CarTilt()
{
    // m_head com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@5f71c76a

    // m_angle com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1d7acb34
    m_angle = 0.0;

}

CarTilt::~CarTilt()
{


}

CarTilt::CarTilt(
        const CarTilt& x)
{
    m_head = x.m_head;
    m_angle = x.m_angle;
}

CarTilt::CarTilt(
        CarTilt&& x) noexcept 
{
    m_head = std::move(x.m_head);
    m_angle = x.m_angle;
}

CarTilt& CarTilt::operator =(
        const CarTilt& x)
{

    m_head = x.m_head;
    m_angle = x.m_angle;

    return *this;
}

CarTilt& CarTilt::operator =(
        CarTilt&& x) noexcept
{

    m_head = std::move(x.m_head);
    m_angle = x.m_angle;

    return *this;
}

bool CarTilt::operator ==(
        const CarTilt& x) const
{

    return (m_head == x.m_head && m_angle == x.m_angle);
}

bool CarTilt::operator !=(
        const CarTilt& x) const
{
    return !(*this == x);
}

size_t CarTilt::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t CarTilt::getCdrSerializedSize(
        const CarTilt& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getCdrSerializedSize(data.head(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void CarTilt::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_head;
    scdr << m_angle;

}

void CarTilt::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_head;
    dcdr >> m_angle;
}

/*!
 * @brief This function copies the value in member head
 * @param _head New value to be copied in member head
 */
void CarTilt::head(
        const Header& _head)
{
    m_head = _head;
}

/*!
 * @brief This function moves the value in member head
 * @param _head New value to be moved in member head
 */
void CarTilt::head(
        Header&& _head)
{
    m_head = std::move(_head);
}

/*!
 * @brief This function returns a constant reference to member head
 * @return Constant reference to member head
 */
const Header& CarTilt::head() const
{
    return m_head;
}

/*!
 * @brief This function returns a reference to member head
 * @return Reference to member head
 */
Header& CarTilt::head()
{
    return m_head;
}
/*!
 * @brief This function sets a value in member angle
 * @param _angle New value for member angle
 */
void CarTilt::angle(
        float _angle)
{
    m_angle = _angle;
}

/*!
 * @brief This function returns the value of member angle
 * @return Value of member angle
 */
float CarTilt::angle() const
{
    return m_angle;
}

/*!
 * @brief This function returns a reference to member angle
 * @return Reference to member angle
 */
float& CarTilt::angle()
{
    return m_angle;
}


size_t CarTilt::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool CarTilt::isKeyDefined()
{
    return false;
}

void CarTilt::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
