// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file engineTemp.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "PacketTypes/engineTemp.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

EngineTemp::EngineTemp()
{
    // m_head com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@5f71c76a

    // m_temp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1d7acb34
    m_temp = 0.0;

}

EngineTemp::~EngineTemp()
{


}

EngineTemp::EngineTemp(
        const EngineTemp& x)
{
    m_head = x.m_head;
    m_temp = x.m_temp;
}

EngineTemp::EngineTemp(
        EngineTemp&& x) noexcept 
{
    m_head = std::move(x.m_head);
    m_temp = x.m_temp;
}

EngineTemp& EngineTemp::operator =(
        const EngineTemp& x)
{

    m_head = x.m_head;
    m_temp = x.m_temp;

    return *this;
}

EngineTemp& EngineTemp::operator =(
        EngineTemp&& x) noexcept
{

    m_head = std::move(x.m_head);
    m_temp = x.m_temp;

    return *this;
}

bool EngineTemp::operator ==(
        const EngineTemp& x) const
{

    return (m_head == x.m_head && m_temp == x.m_temp);
}

bool EngineTemp::operator !=(
        const EngineTemp& x) const
{
    return !(*this == x);
}

size_t EngineTemp::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t EngineTemp::getCdrSerializedSize(
        const EngineTemp& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += Header::getCdrSerializedSize(data.head(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void EngineTemp::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_head;
    scdr << m_temp;

}

void EngineTemp::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_head;
    dcdr >> m_temp;
}

/*!
 * @brief This function copies the value in member head
 * @param _head New value to be copied in member head
 */
void EngineTemp::head(
        const Header& _head)
{
    m_head = _head;
}

/*!
 * @brief This function moves the value in member head
 * @param _head New value to be moved in member head
 */
void EngineTemp::head(
        Header&& _head)
{
    m_head = std::move(_head);
}

/*!
 * @brief This function returns a constant reference to member head
 * @return Constant reference to member head
 */
const Header& EngineTemp::head() const
{
    return m_head;
}

/*!
 * @brief This function returns a reference to member head
 * @return Reference to member head
 */
Header& EngineTemp::head()
{
    return m_head;
}
/*!
 * @brief This function sets a value in member temp
 * @param _temp New value for member temp
 */
void EngineTemp::temp(
        float _temp)
{
    m_temp = _temp;
}

/*!
 * @brief This function returns the value of member temp
 * @return Value of member temp
 */
float EngineTemp::temp() const
{
    return m_temp;
}

/*!
 * @brief This function returns a reference to member temp
 * @return Reference to member temp
 */
float& EngineTemp::temp()
{
    return m_temp;
}


size_t EngineTemp::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool EngineTemp::isKeyDefined()
{
    return false;
}

void EngineTemp::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}
