// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GPSPosition.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_GPSPOSITION_H_
#define _FAST_DDS_GENERATED_GPSPOSITION_H_

#include "header.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(GPSPosition_SOURCE)
#define GPSPosition_DllAPI __declspec( dllexport )
#else
#define GPSPosition_DllAPI __declspec( dllimport )
#endif // GPSPosition_SOURCE
#else
#define GPSPosition_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define GPSPosition_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure GPSPosition defined by the user in the IDL file.
 * @ingroup GPSPOSITION
 */
class GPSPosition
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GPSPosition();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GPSPosition();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GPSPosition that will be copied.
     */
    eProsima_user_DllExport GPSPosition(
            const GPSPosition& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GPSPosition that will be copied.
     */
    eProsima_user_DllExport GPSPosition(
            GPSPosition&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GPSPosition that will be copied.
     */
    eProsima_user_DllExport GPSPosition& operator =(
            const GPSPosition& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GPSPosition that will be copied.
     */
    eProsima_user_DllExport GPSPosition& operator =(
            GPSPosition&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x GPSPosition object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GPSPosition& x) const;

    /*!
     * @brief Comparison operator.
     * @param x GPSPosition object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GPSPosition& x) const;

    /*!
     * @brief This function copies the value in member head
     * @param _head New value to be copied in member head
     */
    eProsima_user_DllExport void head(
            const Header& _head);

    /*!
     * @brief This function moves the value in member head
     * @param _head New value to be moved in member head
     */
    eProsima_user_DllExport void head(
            Header&& _head);

    /*!
     * @brief This function returns a constant reference to member head
     * @return Constant reference to member head
     */
    eProsima_user_DllExport const Header& head() const;

    /*!
     * @brief This function returns a reference to member head
     * @return Reference to member head
     */
    eProsima_user_DllExport Header& head();
    /*!
     * @brief This function sets a value in member lat
     * @param _lat New value for member lat
     */
    eProsima_user_DllExport void lat(
            double _lat);

    /*!
     * @brief This function returns the value of member lat
     * @return Value of member lat
     */
    eProsima_user_DllExport double lat() const;

    /*!
     * @brief This function returns a reference to member lat
     * @return Reference to member lat
     */
    eProsima_user_DllExport double& lat();

    /*!
     * @brief This function sets a value in member lng
     * @param _lng New value for member lng
     */
    eProsima_user_DllExport void lng(
            double _lng);

    /*!
     * @brief This function returns the value of member lng
     * @return Value of member lng
     */
    eProsima_user_DllExport double lng() const;

    /*!
     * @brief This function returns a reference to member lng
     * @return Reference to member lng
     */
    eProsima_user_DllExport double& lng();

    /*!
     * @brief This function sets a value in member alt
     * @param _alt New value for member alt
     */
    eProsima_user_DllExport void alt(
            double _alt);

    /*!
     * @brief This function returns the value of member alt
     * @return Value of member alt
     */
    eProsima_user_DllExport double alt() const;

    /*!
     * @brief This function returns a reference to member alt
     * @return Reference to member alt
     */
    eProsima_user_DllExport double& alt();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const GPSPosition& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    Header m_head;
    double m_lat;
    double m_lng;
    double m_alt;
};

#endif // _FAST_DDS_GENERATED_GPSPOSITION_H_